### PR TITLE
V1730 Config

### PR DESCRIPTION
**Pull request by mastroia**
This version basically takes care of :
- channel_mask 16-bit word readout 
- channel_time 48-bit word for Time64 calculation

### CODE REVIEW

**Comment by darrylmasson** [comment]
I'm going to ask @petergaemers to have a look at this, as he was also working on getting redax to work with the V1730

**Comment by darrylmasson** [comment]
I fixed the merge conflict in V1724.cc. Also @mastroia , please restore the .gitignore file, it keeps a lot of junk files out of the repo.

**Comment by mastroia** [comment]
Hi all,
I restored  the .gitignore file and removed all the commented code.
Shall I close this pull request and open a new one?
Cheers,
Stefano

**Comment by darrylmasson** [comment]
No, I'll merge this once we're done with the current tests we're running.

**Pull request merged**
